### PR TITLE
#166879987 Update TravisCI to run tests

### PR DESCRIPTION
**Pull request by Emmanuel-Dominic**
#### What does this PR do?
- Update TravisCI to run tests

#### Description of Task to be completed?
- [x] Configure the `.travis.yml` file to run the tests with TravisCI

#### How should this be manually tested?
- [x] Visit `https://travis-ci.com/andela/ah-frontend-kronos/branches` to see the travis test run on various branches

#### What are the relevant pivotal tracker stories?
- [#166879987](https://www.pivotaltracker.com/n/projects/2358027/stories/166879987)

#### Screenshots.
Screenshot 2019-07-04 at 22 31 06

### CODE REVIEW

**Review by reifred — APPROVED** [review]

**Review by Rhytah — CHANGES_REQUESTED** [review]
@Emmanuel-Dominic well done on updating TravisCI configurations and the build is passing.
Could you for the meantime disconnect `cirleCI` as we do not have configurations setup for it yet.
This will have all checks for PR passing as per set standard to approve merge

**Comment by Emmanuel-Dominic** [comment]
> @Emmanuel-Dominic well done on updating TravisCI configurations and the build is passing.
> Could you for the meantime disconnect `cirleCI` as we do not have configurations setup for it yet.
> This will have all checks for PR passing as per set standard to approve merge

Yes @Rhytah, `Circle Ci` is currently off in connection with this Repo and i am just waiting for updates or even just re-establish the PR to make the error disappear.

**Review by Rhytah — APPROVED** [review]
@Emmanuel-Dominic well done on updating TravisCI configurations and the build is passing.

**Review by Manorlds-Eaglespark — APPROVED** [review]
Tested and runs well.

**Pull request merged**
