### PR TITLE
#166880003 Users should be able to like and or dislike articles

### PR DESCRIPTION
**Pull request by reifred**
#### What does this PR do?
- Enable authenticated users to like and dislike articles 
#### Description of Task to be completed?
- Let's appreciate those authors who go out of their way to create good content with a Like and encourage those authors who do not meet our expectations with a dislike.
#### How should this be manually tested?
- Visit this [link](https://ah-frontend-kronos-stagi-pr-22.herokuapp.com/)
- Log in using your credentials and like or dislike any article.
##### OR 
- Clone this repo and switch to this branch.
- Start the application using `npm start`
- Log in to the application and like or dislike any article of your choice.

#### What are the relevant pivotal tracker stories?
[#166880003](https://www.pivotaltracker.com/story/show/166880003)

#### Screenshots (If available).
Like/Dislike buttons disabled for un-authenticated users.
image
Like/Dislike buttons enabled for authenticated users.
image
Authenticated users can not dislike the same article again.
image
Authenticated users can not like the same article again.
image

### CODE REVIEW

**Comment by Manorlds-Eaglespark** [comment]
I have a few comments on the UI/UX. When someone clicks on the Like/Dislike button, they are redirected to a different page, this can be improved.

**Comment by Manorlds-Eaglespark** [comment]
Are the thumbs up and down about the time to read the article or they are independant, kindly clarify in the UI
Screenshot 2019-07-30 at 13 41 31

**Comment by Manorlds-Eaglespark** [comment]
When someone clicks a button on the article when they have not logged in, nothing happens. Add at least a toast with information letting them know that they can only like or dislike an article when they are logged in. 
Screenshot 2019-07-30 at 13 42 05
Or entirely remove the buttons because it may confuse some users.

**Comment by reifred** [comment]
> I have a few comments on the UI/UX. When someone clicks on the Like/Dislike button, they are redirected to a different page, this can be improved.

This cannot be improved because the api does not return the article after a like/dislike but rather a message. In otherwards, you cannot get the new state of the article so that's why I redirect.
This was a recommendation from the TTL after looking into the backend since it needed to redo all backend like/dislike feature.

**Comment by reifred** [comment]
> When someone clicks a button on the article when they have not logged in, nothing happens. Add atleast a toast with information letting them know that they can only like or dislike an article when they are logged in.
> Screenshot 2019-07-30 at 13 42 05

From the screenshot shown, it clearly indicates that the button is disabled for anyone who is not logged in.

**Comment by Manorlds-Eaglespark** [comment]
> > I have a few comments on the UI/UX. When someone clicks on the Like/Dislike button, they are redirected to a different page, this can be improved.
> 
> This cannot be improved because the api does not return the article after a like/dislike but rather a message. In otherwards, you cannot get the new state of the article so that's why I redirect.
> This was a recommendation from the TTL after looking into the backend since it needed to redo all backend like/dislike feature.

I think Redirecting to a different page is independent of getting a response from the server, when using React, together with React-Redux. Redirecting to a different page is not the answer. Atleast reload the same page.

**Comment by reifred** [comment]
> Are the thumbs up and down about the time to read the article or they are independant, kindly clarify in the UI
> Screenshot 2019-07-30 at 13 41 31

Liking of an article is a thumbs-up and disliking is a thumbs-down. There was no change in the articles page done. The UI is as it is supposed to be from the mockups if you could suggest another design kindly work with the team so that we could send them to the PO for approval so that I can improve.

**Comment by Manorlds-Eaglespark** [comment]
> > When someone clicks a button on the article when they have not logged in, nothing happens. Add atleast a toast with information letting them know that they can only like or dislike an article when they are logged in.
> > Screenshot 2019-07-30 at 13 42 05
> 
> From the screenshot shown, it clearly indicates that the button is disabled for anyone who is not logged in.

I was aware of this. Informing users that they need to log in would greatly improve the user experience.

**Comment by reifred** [comment]
> > > When someone clicks a button on the article when they have not logged in, nothing happens. Add atleast a toast with information letting them know that they can only like or dislike an article when they are logged in.
> > > Screenshot 2019-07-30 at 13 42 05
> > 
> > 
> > From the screenshot shown, it clearly indicates that the button is disabled for anyone who is not logged in.
> 
> I was aware of this. Informing users that they need to log in would greatly improve the user experience.

I don't think that will be good having many toast messages for every click.

**Comment by Manorlds-Eaglespark** [comment]
> > Are the thumbs up and down about the time to read the article or they are independant, kindly clarify in the UI
> > Screenshot 2019-07-30 at 13 41 31
> 
> Liking of an article is a thumbs-up and disliking is a thumbs-down. There was no change in the articles page done. The UI is as it is supposed to be from the mockups if you could suggest another design kindly work with the team so that we could send them to the PO for approval so that I can improve.

Well, you could solve this by adding more space, a comma to separate those two pieces of data for clarity to the end-users. Please reply in the correct spirit of receiving feedback.

**Comment by reifred** [comment]
> > > I have a few comments on the UI/UX. When someone clicks on the Like/Dislike button, they are redirected to a different page, this can be improved.
> > 
> > 
> > This cannot be improved because the api does not return the article after a like/dislike but rather a message. In otherwards, you cannot get the new state of the article so that's why I redirect.
> > This was a recommendation from the TTL after looking into the backend since it needed to redo all backend like/dislike feature.
> 
> I think Redirecting to a different page is independent of getting a response from the server, when using React, together with React-Redux. Redirecting to a different page is not the answer. Atleast reload the same page.

Sure will sync with you on it. Thanks.

**Comment by reifred** [comment]
> > > I have a few comments on the UI/UX. When someone clicks on the Like/Dislike button, they are redirected to a different page, this can be improved.
> > 
> > 
> > This cannot be improved because the api does not return the article after a like/dislike but rather a message. In otherwards, you cannot get the new state of the article so that's why I redirect.
> > This was a recommendation from the TTL after looking into the backend since it needed to redo all backend like/dislike feature.
> 
> I think Redirecting to a different page is independent of getting a response from the server, when using React, together with React-Redux. Redirecting to a different page is not the answer. Atleast reload the same page.

This has been worked upon.

**Review by Emmanuel-Dominic — APPROVED** [review]
@reifred, Thanks for the great work, i have tested this feature and it is working well.

**Review by Rhytah — APPROVED** [review]

**Review by Manorlds-Eaglespark — APPROVED** [review]
Good work, the feature can be merged.

**Review by kcharles52 — APPROVED** [review]

**Pull request merged**
