### PR TITLE
#166880014 Users should be able to report an article

### PR DESCRIPTION
**Pull request by Manorlds-Eaglespark**
#### What does this PR do?
Users should be able to report an article

#### Description of Task to be completed?
As an authenticated user I should be able to report articles that violate terms of the agreement or are plagiarised to the authors haven admin for removal and or any other actions as per the terms of engagement. Let's get creative in the way that we display the ability to do reporting on the frontend

#### How should this be manually tested?
Follow the setup steps on the [readme page](https://github.com/andela/ah-frontend-kronos) of this repo to set-up locally, you will before logging in, the article page has a note that tells you to log in to report abuse. When logged in, you can interact with the report abuse button below an article.

#### What are the relevant pivotal tracker stories?
[#166880014](https://www.pivotaltracker.com/story/show/166880014)

#### Screenshots (if appropriate)
Screenshot 2019-08-01 at 15 32 19
Screenshot 2019-08-01 at 15 32 55
Screenshot 2019-08-01 at 15 33 16

### CODE REVIEW

**Review by reifred — CHANGES_REQUESTED** [review]
Thanks @Manorlds-Eaglespark, for the work done but I get this error when I visit the deployment link.
image

**Comment by Manorlds-Eaglespark** [comment]
> Thanks @Manorlds-Eaglespark, for the work done but I get this error when I visit the deployment link.
> image

That error is not in the scope of this feature so it may not be relevant. Kindly look in the files changed to clarify this. Thanks

**Review by reifred — CHANGES_REQUESTED** [review]
Thanks @Manorlds-Eaglespark for the good work done on reporting an article. I suggest that you remove this default message that is displayed if a user is not authenticated.
image

**Comment by Manorlds-Eaglespark** [comment]
> Thanks @Manorlds-Eaglespark for the good work done on reporting an article. I suggest that you remove this default message that is displayed if a user is not authenticated.
> image

What would you prefer I change it for you instead?

**Comment by reifred** [comment]
> > Thanks @Manorlds-Eaglespark for the good work done on reporting an article. I suggest that you remove this default message that is displayed if a user is not authenticated.
> > image
> 
> What would you prefer I change it for you instead?

You could just remove it since that functionality is for only authenticated users.

**Comment by Rhytah** [comment]
@Manorlds-Eaglespark Great work on the feature, just to add to @reifred's request. we can have the button instead of the text just as seen when I log in, 
Where is the report sent after creation, do we have a view for these reports? 
Would be nice to have a full flow of reporting scenario.

**Comment by Manorlds-Eaglespark** [comment]
> > > Thanks @Manorlds-Eaglespark for the good work done on reporting an article. I suggest that you remove this default message that is displayed if a user is not authenticated.
> > > image
> > 
> > 
> > What would you prefer I change it for you instead?
> 
> You could remove just remove it since that functionality is for only authenticated users.

I have removed the text.

**Comment by Manorlds-Eaglespark** [comment]
> @Manorlds-Eaglespark Great work on the feature, just to add to @reifred's request. we can have the button instead of the text just as seen when I log in,
> Where is the report sent after creation, do we have a view for these reports?
> Would be nice to have a full flow of reporting scenario.

Thanks for sharing your thoughts on this, however, it has been resolved, thanks.

**Comment by reifred** [comment]
Thanks, @Manorlds-Eaglespark for working on the requested changes. Though after making my report I can't be sure if it was added since I don't have a view of seeing my created reports. I think you should consider looking into @Rhytah's comment too.

**Comment by Manorlds-Eaglespark** [comment]
> Thanks, @Manorlds-Eaglespark for working on the requested changes. Though after making my report I can't be sure if it was added since I don't have a view of seeing my created reports. I think you should consider looking into @Rhytah's comment too.

The API is limited on that Issue. But according to the feature requirement, [here](https://www.pivotaltracker.com/story/show/166880014). Only a text input box for this feature is required. @Rhytah 's suggesting was resolved when I removed the text entirely, mostly on the recommendation of @kcharles52

**Review by reifred — APPROVED** [review]

**Comment by reifred** [comment]
> > Thanks, @Manorlds-Eaglespark for working on the requested changes. Though after making my report I can't be sure if it was added since I don't have a view of seeing my created reports. I think you should consider looking into @Rhytah's comment too.
> 
> The API is limited on that Issue. But according to the feature requirement, [here](https://www.pivotaltracker.com/story/show/166880014). Only a text input box for this feature is required. @Rhytah 's suggesting was resolved when I removed the text entirely, mostly on the recommendation of @kcharles52

Ok then thanks for the good work.

**Review by Rhytah — APPROVED** [review]

**Pull request merged**
