### PR TITLE
#166879985 Setup Redux

### PR DESCRIPTION
**Pull request by Rhytah**
#### What does this PR do?
- Setup Redux

#### Description of Task to be completed?

- [x] - install redux
- [x] - install react-redux
- [x] - install redux-devtools-extension
- [x] - create appropriate file structure for React/Redux workflow

#### How should this be manually tested?
- Install updated dependencies by running `npm i` command
- Start the server by running `npm start` command
- Go to open index page and right click to display options to `inspect` page
- A developer panel will open. Go to the redux tab

#### What are the relevant pivotal tracker stories?
[#166879985](https://www.pivotaltracker.com/story/show/166879985)

#### Screenshots
Redux devtools panel open to show a change in state

Screenshot 2019-07-08 at 11 36 39

### CODE REVIEW

**Review by reifred — APPROVED** [review]
Thanks @Rhytah  for setting up redux.

**Review by Emmanuel-Dominic — APPROVED** [review]

**Review by Manorlds-Eaglespark — APPROVED** [review]

**Review by Yiga-fred — COMMENTED** [review]
The folder structure can be improved let's talk about it during standups

**Review by Yiga-fred — CHANGES_REQUESTED** [review]
Good work but move remove the __tests__ folder from the reducers folder and create a folder named reducers inside the tests folder it will house all tests related to reducers, in addition, rename the __tests__  folder to tests

**Comment by Rhytah** [comment]
> Good work but move remove the **tests** folder from the reducers folder and create a folder named reducers inside the tests folder it will house all tests related to reducers, in addition, rename the **tests** folder to tests

@Yiga-fred this has been resolved.

**Review by Yiga-fred — APPROVED** [review]
LGTM

**Pull request merged**
